//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5448.
// 
namespace HTN.BITS.FGTRACK.FGPRESS.ServiceRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_FGPRESSSoap", Namespace="http://tempuri.org/")]
    public partial class Service_FGPRESS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service_FGPRESS() {
            this.Url = "http://192.168.10.95/FGTrackService/Service_FGPRESS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckValidationUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckValidationUser(string userid) {
            object[] results = this.Invoke("CheckValidationUser", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckValidationUser(string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckValidationUser", new object[] {
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckValidationUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdatePC_FG_In", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCard GetUpdatePC_FG_In(string serialNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetUpdatePC_FG_In", new object[] {
                        serialNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUpdatePC_FG_In(string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUpdatePC_FG_In", new object[] {
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductCard EndGetUpdatePC_FG_In(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPickInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PickQty GetPickInfo(string pickNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetPickInfo", new object[] {
                        pickNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((PickQty)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPickInfo(string pickNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPickInfo", new object[] {
                        pickNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public PickQty EndGetPickInfo(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((PickQty)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdatePCPicking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCard GetUpdatePCPicking(string pickNo, string serialNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetUpdatePCPicking", new object[] {
                        pickNo,
                        serialNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUpdatePCPicking(string pickNo, string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUpdatePCPicking", new object[] {
                        pickNo,
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductCard EndGetUpdatePCPicking(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoadInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoadQty GetLoadInfo(string loadNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetLoadInfo", new object[] {
                        loadNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((LoadQty)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLoadInfo(string loadNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLoadInfo", new object[] {
                        loadNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public LoadQty EndGetLoadInfo(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((LoadQty)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdatePCLoading", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCard GetUpdatePCLoading(string loadNo, string serialNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetUpdatePCLoading", new object[] {
                        loadNo,
                        serialNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUpdatePCLoading(string loadNo, string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUpdatePCLoading", new object[] {
                        loadNo,
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductCard EndGetUpdatePCLoading(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLoadingSeal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateLoadingSeal(string loadNo, string userid) {
            object[] results = this.Invoke("UpdateLoadingSeal", new object[] {
                        loadNo,
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateLoadingSeal(string loadNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateLoadingSeal", new object[] {
                        loadNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdateLoadingSeal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductCardStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCardStatusFG GetProductCardStatus(string serialNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetProductCardStatus", new object[] {
                        serialNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((ProductCardStatusFG)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductCardStatus(string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductCardStatus", new object[] {
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductCardStatusFG EndGetProductCardStatus(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((ProductCardStatusFG)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQCReturnOrderInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QCReturn GetQCReturnOrderInfo(string qcReturnNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetQCReturnOrderInfo", new object[] {
                        qcReturnNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((QCReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetQCReturnOrderInfo(string qcReturnNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetQCReturnOrderInfo", new object[] {
                        qcReturnNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public QCReturn EndGetQCReturnOrderInfo(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((QCReturn)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReturnProductCardInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCard GetReturnProductCardInfo(string qcReturnNo, string serialNo, string userid, out string resultMsg) {
            object[] results = this.Invoke("GetReturnProductCardInfo", new object[] {
                        qcReturnNo,
                        serialNo,
                        userid});
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReturnProductCardInfo(string qcReturnNo, string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReturnProductCardInfo", new object[] {
                        qcReturnNo,
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductCard EndGetReturnProductCardInfo(System.IAsyncResult asyncResult, out string resultMsg) {
            object[] results = this.EndInvoke(asyncResult);
            resultMsg = ((string)(results[1]));
            return ((ProductCard)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateReturnProductCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateReturnProductCard(string qcReturnNo, string serialNo, string userid, out int totalBox) {
            object[] results = this.Invoke("UpdateReturnProductCard", new object[] {
                        qcReturnNo,
                        serialNo,
                        userid});
            totalBox = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateReturnProductCard(string qcReturnNo, string serialNo, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateReturnProductCard", new object[] {
                        qcReturnNo,
                        serialNo,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdateReturnProductCard(System.IAsyncResult asyncResult, out int totalBox) {
            object[] results = this.EndInvoke(asyncResult);
            totalBox = ((int)(results[1]));
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductCardStatusFG))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductCard {
        
        private string sERIAL_NOField;
        
        private string pROD_SEQ_NOField;
        
        private string pRODUCT_NOField;
        
        private string pRODUCT_NAMEField;
        
        private string mTL_TYPEField;
        
        private string jOB_NOField;
        
        private string jOB_LOTField;
        
        private string sHIFTField;
        
        private int lINE_NOField;
        
        private string mC_NOField;
        
        private int qTYField;
        
        private int bOX_QTYField;
        
        private int bOX_SCANNEDField;
        
        private int aSG_NGField;
        
        private int nG_QTYField;
        
        private string uNIT_IDField;
        
        /// <remarks/>
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        public string PROD_SEQ_NO {
            get {
                return this.pROD_SEQ_NOField;
            }
            set {
                this.pROD_SEQ_NOField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_NO {
            get {
                return this.pRODUCT_NOField;
            }
            set {
                this.pRODUCT_NOField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_NAME {
            get {
                return this.pRODUCT_NAMEField;
            }
            set {
                this.pRODUCT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MTL_TYPE {
            get {
                return this.mTL_TYPEField;
            }
            set {
                this.mTL_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string JOB_NO {
            get {
                return this.jOB_NOField;
            }
            set {
                this.jOB_NOField = value;
            }
        }
        
        /// <remarks/>
        public string JOB_LOT {
            get {
                return this.jOB_LOTField;
            }
            set {
                this.jOB_LOTField = value;
            }
        }
        
        /// <remarks/>
        public string SHIFT {
            get {
                return this.sHIFTField;
            }
            set {
                this.sHIFTField = value;
            }
        }
        
        /// <remarks/>
        public int LINE_NO {
            get {
                return this.lINE_NOField;
            }
            set {
                this.lINE_NOField = value;
            }
        }
        
        /// <remarks/>
        public string MC_NO {
            get {
                return this.mC_NOField;
            }
            set {
                this.mC_NOField = value;
            }
        }
        
        /// <remarks/>
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public int BOX_QTY {
            get {
                return this.bOX_QTYField;
            }
            set {
                this.bOX_QTYField = value;
            }
        }
        
        /// <remarks/>
        public int BOX_SCANNED {
            get {
                return this.bOX_SCANNEDField;
            }
            set {
                this.bOX_SCANNEDField = value;
            }
        }
        
        /// <remarks/>
        public int ASG_NG {
            get {
                return this.aSG_NGField;
            }
            set {
                this.aSG_NGField = value;
            }
        }
        
        /// <remarks/>
        public int NG_QTY {
            get {
                return this.nG_QTYField;
            }
            set {
                this.nG_QTYField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT_ID {
            get {
                return this.uNIT_IDField;
            }
            set {
                this.uNIT_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QCReturn {
        
        private string wH_IDField;
        
        private string rT_NOField;
        
        private int nO_OF_LABELField;
        
        /// <remarks/>
        public string WH_ID {
            get {
                return this.wH_IDField;
            }
            set {
                this.wH_IDField = value;
            }
        }
        
        /// <remarks/>
        public string RT_NO {
            get {
                return this.rT_NOField;
            }
            set {
                this.rT_NOField = value;
            }
        }
        
        /// <remarks/>
        public int NO_OF_LABEL {
            get {
                return this.nO_OF_LABELField;
            }
            set {
                this.nO_OF_LABELField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadQty {
        
        private string lOADING_NOField;
        
        private int lOADED_BOXField;
        
        private int lOADED_QTYField;
        
        /// <remarks/>
        public string LOADING_NO {
            get {
                return this.lOADING_NOField;
            }
            set {
                this.lOADING_NOField = value;
            }
        }
        
        /// <remarks/>
        public int LOADED_BOX {
            get {
                return this.lOADED_BOXField;
            }
            set {
                this.lOADED_BOXField = value;
            }
        }
        
        /// <remarks/>
        public int LOADED_QTY {
            get {
                return this.lOADED_QTYField;
            }
            set {
                this.lOADED_QTYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PickQty {
        
        private string pICK_NOField;
        
        private int qTYField;
        
        private int pICKED_QTYField;
        
        private string uNIT_IDField;
        
        /// <remarks/>
        public string PICK_NO {
            get {
                return this.pICK_NOField;
            }
            set {
                this.pICK_NOField = value;
            }
        }
        
        /// <remarks/>
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public int PICKED_QTY {
            get {
                return this.pICKED_QTYField;
            }
            set {
                this.pICKED_QTYField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT_ID {
            get {
                return this.uNIT_IDField;
            }
            set {
                this.uNIT_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductCardStatusFG : ProductCard {
        
        private string whField;
        
        private string sTATUSField;
        
        private string pROCESS_NOField;
        
        private System.Nullable<System.DateTime> pROCESS_DATEField;
        
        private string oRI_LABELField;
        
        private int bREAK_QTYField;
        
        /// <remarks/>
        public string WH {
            get {
                return this.whField;
            }
            set {
                this.whField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_NO {
            get {
                return this.pROCESS_NOField;
            }
            set {
                this.pROCESS_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PROCESS_DATE {
            get {
                return this.pROCESS_DATEField;
            }
            set {
                this.pROCESS_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string ORI_LABEL {
            get {
                return this.oRI_LABELField;
            }
            set {
                this.oRI_LABELField = value;
            }
        }
        
        /// <remarks/>
        public int BREAK_QTY {
            get {
                return this.bREAK_QTYField;
            }
            set {
                this.bREAK_QTYField = value;
            }
        }
    }
}
