//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTN.BITS.MSC.SCN.UIL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTN.BITS.MSC.SCN.UIL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader_blue_32 {
            get {
                object obj = ResourceManager.GetObject("ajax_loader_blue_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_1 {
            get {
                object obj = ResourceManager.GetObject("Battery_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_2 {
            get {
                object obj = ResourceManager.GetObject("Battery_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_3 {
            get {
                object obj = ResourceManager.GetObject("Battery_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_4 {
            get {
                object obj = ResourceManager.GetObject("Battery_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_5 {
            get {
                object obj = ResourceManager.GetObject("Battery_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_6 {
            get {
                object obj = ResourceManager.GetObject("Battery_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CI_PutAway {
            get {
                object obj = ResourceManager.GetObject("CI_PutAway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CI_Receiving {
            get {
                object obj = ResourceManager.GetObject("CI_Receiving", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CO_Loading {
            get {
                object obj = ResourceManager.GetObject("CO_Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CO_Picking {
            get {
                object obj = ResourceManager.GetObject("CO_Picking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back1 {
            get {
                object obj = ResourceManager.GetObject("F_Back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back2 {
            get {
                object obj = ResourceManager.GetObject("F_Back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back3 {
            get {
                object obj = ResourceManager.GetObject("F_Back3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back4 {
            get {
                object obj = ResourceManager.GetObject("F_Back4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back5 {
            get {
                object obj = ResourceManager.GetObject("F_Back5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back6 {
            get {
                object obj = ResourceManager.GetObject("F_Back6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back7 {
            get {
                object obj = ResourceManager.GetObject("F_Back7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back8 {
            get {
                object obj = ResourceManager.GetObject("F_Back8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Back9 {
            get {
                object obj = ResourceManager.GetObject("F_Back9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_CargoIn {
            get {
                object obj = ResourceManager.GetObject("F_CargoIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_CargoOut {
            get {
                object obj = ResourceManager.GetObject("F_CargoOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_QC {
            get {
                object obj = ResourceManager.GetObject("F_QC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Setting {
            get {
                object obj = ResourceManager.GetObject("F_Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_Utility {
            get {
                object obj = ResourceManager.GetObject("F_Utility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_Line {
            get {
                object obj = ResourceManager.GetObject("H_Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_User1 {
            get {
                object obj = ResourceManager.GetObject("H_User1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_User2 {
            get {
                object obj = ResourceManager.GetObject("H_User2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_User3 {
            get {
                object obj = ResourceManager.GetObject("H_User3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_User4 {
            get {
                object obj = ResourceManager.GetObject("H_User4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H_User5 {
            get {
                object obj = ResourceManager.GetObject("H_User5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_AC {
            get {
                object obj = ResourceManager.GetObject("Icon_AC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Battery {
            get {
                object obj = ResourceManager.GetObject("Icon_Battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_CargoIn {
            get {
                object obj = ResourceManager.GetObject("Icon_CargoIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_CargoOut {
            get {
                object obj = ResourceManager.GetObject("Icon_CargoOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Connect {
            get {
                object obj = ResourceManager.GetObject("Icon_Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_DotGray {
            get {
                object obj = ResourceManager.GetObject("Icon_DotGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_DotGreen {
            get {
                object obj = ResourceManager.GetObject("Icon_DotGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Exit {
            get {
                object obj = ResourceManager.GetObject("Icon_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Location {
            get {
                object obj = ResourceManager.GetObject("Icon_Location", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_QC {
            get {
                object obj = ResourceManager.GetObject("Icon_QC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_QTY {
            get {
                object obj = ResourceManager.GetObject("Icon_QTY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Setting {
            get {
                object obj = ResourceManager.GetObject("Icon_Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_User {
            get {
                object obj = ResourceManager.GetObject("Icon_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_User2 {
            get {
                object obj = ResourceManager.GetObject("Icon_User2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Utility {
            get {
                object obj = ResourceManager.GetObject("Icon_Utility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QC_Hold {
            get {
                object obj = ResourceManager.GetObject("QC_Hold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QC_NG {
            get {
                object obj = ResourceManager.GetObject("QC_NG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QC_UnHold {
            get {
                object obj = ResourceManager.GetObject("QC_UnHold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SplashInitScanner {
            get {
                object obj = ResourceManager.GetObject("SplashInitScanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ST_EN {
            get {
                object obj = ResourceManager.GetObject("ST_EN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ST_Language {
            get {
                object obj = ResourceManager.GetObject("ST_Language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ST_TH {
            get {
                object obj = ResourceManager.GetObject("ST_TH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap updateBG {
            get {
                object obj = ResourceManager.GetObject("updateBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UT_CheckLabel {
            get {
                object obj = ResourceManager.GetObject("UT_CheckLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UT_Relocation {
            get {
                object obj = ResourceManager.GetObject("UT_Relocation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
