SELECT
    PARTY_ID,
    PARTY_NAME,
    WH_ID,
    PRODUCT_NO,
    PRODUCT_NAME,
    PRODUCT_TYPE_ID,
    CASE ("PRODUCT_TYPE_ID")
    WHEN "H" THEN "HOR"
    WHEN "V" THEN "VER"
    WHEN "T" THEN "TAM"
    ELSE "PRS"
    END AS PRODUCT_TYPE_NAME,
    BOX_QTY,
    QTY,
    NO_OF_BOX,
    MAX(FLAG)
FROM STOCK_BY_CUSTOMER
GROUP BY PARTY_ID,
	 PARTY_NAME,
	 WH_ID,
	 PRODUCT_NO,
	 PRODUCT_TYPE_ID,
	 PRODUCT_TYPE_NAME,
	 BOX_QTY,
	 QTY,
	 NO_OF_BOX; 

